---
title: "Getting and Cleaning Data Course Project"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents


The script run_analysis.R downloads the data for the project from:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

Unzips the documents and uploads in R all the relevant data sets.
As requested, merges the train and test set into one data set by using rbind and cbind commands.
Extracts only the measurements on the mean and standard deviation for each measurement by creating first a  vector for subsetting the relevant columns (string manipulation commands and regex expressions were used as grep and \\b.....\\ ). 
After the previous step, activities are added by merging two data sets: mergedsets_subsetted and Activities. This step covers using descriptive activity names to activities.

Then appropriate descriptive variable names are given by using string manipulation commands and regex expressions as gsub and str_replace_all.

In order to get a second, independent tidy data set with the average of each variable for each activity and each subject, the data set is grouped (group_by command) by both Activity and Subject variables and summarized (summarize command) using the mean function. Then a txt file is generated with the write.table command.

Lastly, all accesory data sets are removed from the environment.

